### PR TITLE
Converted Skin to Mediawiki 1.20 style

### PR DESCRIPTION
**Pull request by billwashere**
This pull request converts Mediawiki 1.20 style but it won't work for older versions.

Tested on Mediawiki 1.26.2. 

Add the following to your LocalSettings.php to load it.
wfLoadSkin( 'ScummModern' );

### CODE REVIEW

**Comment by criezy** [comment]
Thank you.
I do however have an issue when I am trying to use this skin with mediawiki 1.26.2. I mostly work but I am getting this warning:
Warning: OutputPage::getModuleStyles: style module should define its position explicitly: skins.scummmodern ResourceLoaderFileModule [Called from OutputPage::getModuleStyles in /Users/criezy/Sites/wiki/includes/OutputPage.php at line 623] in /Users/criezy/Sites/wiki/includes/debug/MWDebug.php on line 300

Any idea what the issue is?

**Comment by billwashere** [comment]
Oops. 

I believe that there is a small mistake in skin.json

``` javascript
"skins.scummmodern": {

            "styles": {

                        "scummmodern/menu.css": { "media": "screen" },

                        "scummmodern/layout.css": { "media": "screen" },

                        "scummmodern/chart.css": { "media": "screen" }

            }

        },
```

Should be 

``` javascript
"skins.scummmodern": {
    "position" : "top", 
            "styles": {

                        "scummmodern/menu.css": { "media": "screen" },

                        "scummmodern/layout.css": { "media": "screen" },

                        "scummmodern/chart.css": { "media": "screen" }

            }

        },
```

**Comment by billwashere** [comment]
Sorry, I didn't get a chance to test the fix above and I am a little busy at atm. I'll check it in a few days if there is any other warnings.

**Comment by criezy** [comment]
I tested quickly and the fix above seems to work. I don't see any warnings now.

**Comment by criezy** [comment]
After further testings it appears to be all good now.
Thanks a lot.

**Pull request merged**
